# -*- coding: utf-8 -*-
"""데이터정제(hj).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CDMCeOx4pD79Rq8Aap5rlV-7NvZvK35-
"""

from google import colab

import pandas as pd
import numpy as np
import io
import matplotlib.pyplot as plt
import os

os.chdir('/content/drive/MyDrive/대외활동/암빅데이터경진대회/Validation')

df = pd.read_csv('/content/drive/MyDrive/대외활동/암빅데이터경진대회/Validation/유방암 합성데이터.csv')
#/content/drive/MyDrive/대외활동/암빅데이터경진대회/Validation/유방암 합성데이터.csv

"""정제 data 만들기"""

# 항암 환자 데이터 추출
df_ch=df[(df['Chemotherapy']==1)]
# 불필요 열 삭제
df_ch.drop(["Death","Survival period","No"], axis=1,inplace=True)

# 폐경 나이 오류 데이터 제거
false_index=df_ch[(df_ch["Age of Menarch"]>df_ch["Age of Menopause"]) | (df_ch["AGE"]<df_ch["Age of Menopause"])].index
df_true=df_ch.drop(false_index)

df_true.to_csv("/content/drive/MyDrive/대외활동/암빅데이터경진대회/Validation/항암환자new.csv",index=None)
