# -*- coding: utf-8 -*-
"""4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fGKKRhZcryqElePaWKg21msAL0ejDsg9
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/암빅데이터경진대회/Train/train.csv')

df_병리=df[['AGE','inductal carcinoma','infiltrating duct carcinoma','adenocarcinoma','lobular carcinoma','Metaplastic carcinoma','병기(t)','병기(n)','병기(m)','Height','Weight','BRCA1 PVs','BRCA1 VUS','BRCA2 PVs','BRCA2 VUS','ER','PR','AR']]
df_병리.to_csv("/content/drive/MyDrive/암빅데이터경진대회/Train/train_병리.csv",index=None)

df_생활=df[['Type of Drink','Smoke','COCP','HRT']]
df_생활.to_csv("/content/drive/MyDrive/암빅데이터경진대회/Train/train_생활.csv",index=None)

df_사회=df[['Marriage','Age at first birth','Number of births']]
df_사회.to_csv("/content/drive/MyDrive/암빅데이터경진대회/Train/train_사회.csv",index=None)

df_치료=df[['BCS','Mestectomy','pan hysterosalpingo oophorectomy','Hormone therapy','Radiation Therapy']]
df_치료.to_csv("/content/drive/MyDrive/암빅데이터경진대회/Train/train_치료.csv",index=None)