# -*- coding: utf-8 -*-
"""SVM_최종.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18l1-_EZAtzKuaXTXuSf2Ttacp0kwBtBM

# Data & Module import
"""

import pandas as pd
import sklearn
import os

# 자기 파일 경로로 바꿔서 쓸 것
os.chdir("/content/drive/MyDrive/암빅데이터경진대회")

train = pd.read_csv("./Train/train.csv")

valid = pd.read_csv("./Validation/valid.csv")

train

len(train)

"""## 조기폐경 label 추가 (SVC)
regression의 경우에는 밑의 과정 필요 x
"""

train["Early Menopause"] = 0

# 40세 미만 폐경 -> label 1로

for i in range(len(train)):
  if (train.iloc[i,9]<40):
    train.iloc[i,33] = 1

# 원래 폐경 열은 drop

train = train.drop("Age of Menopause",axis=1)
train

# validation data

valid["Early Menopause"] = 0

for i in range(len(valid)):
  if (valid.iloc[i,9]<40):
    valid.iloc[i,33] = 1

valid = valid.drop("Age of Menopause",axis=1)
valid

"""# X,Y 분리

## Classification
"""

x_train = train.drop("Early Menopause",axis=1)
y_train = train.iloc[:,32:33]

x_valid = valid.drop("Early Menopause",axis=1)
y_valid = valid.iloc[:,32:33]

y_valid

"""## Regression"""

x_train = train.drop("Age of Menopause",axis=1)
y_train = train.iloc[:,9:10]

x_valid = valid.drop("Age of Menopause",axis=1)
y_valid = valid.iloc[:,9:10]

y_valid

"""## 4 Groups"""

x_병리 = x_train[['AGE','inductal carcinoma','infiltrating duct carcinoma','adenocarcinoma','lobular carcinoma','Metaplastic carcinoma','병기(t)','병기(n)','병기(m)','Height','Weight','BRCA1 PVs','BRCA1 VUS','BRCA2 PVs','BRCA2 VUS','ER','PR','AR']]

x_생활 = x_train[['Type of Drink','Smoke','COCP','HRT']]

x_사회 = x_train[['Marriage','Age at first birth','Number of births']]

x_치료 = x_train[['BCS','Mestectomy','pan hysterosalpingo oophorectomy','Hormone therapy','Radiation Therapy']]

# to csv
x_병리.to_csv("/content/drive/MyDrive/암빅데이터경진대회/Train/x_병리.csv",index=None)
x_생활.to_csv("/content/drive/MyDrive/암빅데이터경진대회/Train/x_병리.csv",index=None)
x_사회.to_csv("/content/drive/MyDrive/암빅데이터경진대회/Train/x_병리.csv",index=None)
x_치료.to_csv("/content/drive/MyDrive/암빅데이터경진대회/Train/x_병리.csv",index=None)

x_병리_val = x_valid[['AGE','inductal carcinoma','infiltrating duct carcinoma','adenocarcinoma','lobular carcinoma','Metaplastic carcinoma','병기(t)','병기(n)','병기(m)','Height','Weight','BRCA1 PVs','BRCA1 VUS','BRCA2 PVs','BRCA2 VUS','ER','PR','AR']]
x_생활_val = x_valid[['Type of Drink','Smoke','COCP','HRT']]
x_사회_val = x_valid[['Marriage','Age at first birth','Number of births']]
x_치료_val = x_valid[['BCS','Mestectomy','pan hysterosalpingo oophorectomy','Hormone therapy','Radiation Therapy']]

"""# SVM model

## SVC
"""

from sklearn.model_selection import GridSearchCV, cross_validate
from sklearn.svm import SVC

svc = SVC(verbose=True, random_state = 77)

svc

"""## SVR"""

from sklearn.svm import SVR

svr = SVR(verbose=True)

svr

"""## GridSearchCV
가장 적절한 parameter 값 찾기
"""

import warnings
warnings.filterwarnings(action='ignore')

MAE = 'neg_mean_absolute_error'

params = {'kernel':["linear", "poly", "rbf", "sigmoid"]}

params = {'C':[1.0,2.0,3.0]}

grid_search = GridSearchCV(svc, params, scoring=MAE, cv=5, verbose=3, return_train_score=True)

grid_search.fit(x_train,y_train)

print("최적 파라미터: ",grid_search.best_params_)
print("best score : ",-1*(grid_search.best_score_))

"""# Train & Predict

## SVC
"""

svc.fit(x_병리,y_train)

pred = svc.predict(x_병리_val)

pred

"""## SVR"""

svr.fit(x_train, y_train)

pred = svr.predict(x_valid)

pred

# 평균에러

pred_df = pd.DataFrame(pred)
pred_df.columns=["Age of Menopause"]

error = pd.DataFrame(pred_df - y_valid)

error_avg = error["Age of Menopause"].mean()
print("Average error: ", error_avg)

"""# KFold
10-fold Cross Validation
"""

from sklearn.model_selection import KFold
kfold = KFold(n_splits=10,shuffle=False)

mean_error_df = pd.DataFrame(columns=["pred","error"])

for train_index, validate_index in kfold.split(x_train):
    x_tr, x_val = x_train.iloc[train_index,:], x_train.iloc[validate_index,:]
    y_tr, y_val = y_train.iloc[train_index], y_train.iloc[validate_index]

    svc.fit(x_tr,y_tr)
    y_pred = svc.predict(x_val)
    mean_error = pd.DataFrame(y_pred-y_val)
    
    mean_error.columns=["error"]
    
    df_concat = pd.concat([y_val,mean_error],axis=1)
    
    mean_error_df = mean_error_df.append(df_concat)
