# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IA8eHV3UWmdDP_jRFFxcQZad2Y8zeeZT
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/암빅데이터경진대회/Train/학습데이터_유방암.csv')
del df['No']

#correlation
corr=df.corr(method='pearson')
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
print(corr)
max(corr)

key=df.keys()
dataf=[]
#AGE EDA: number
age_sum=0
age_min=99
age_max=0
for i in range(len(df)):
  age_sum+=df['AGE'][i]
  if df['AGE'][i]<age_min:
    age_min=df['AGE'][i]
  elif df['AGE'][i]>age_max:
    age_max=df['AGE'][i]
print(age_sum/len(df))
print(age_min)
print(age_max)

#inductal carcinoma~M1b EDA: bool
di_1={}
for i in range(1,34):
  no=0
  yes=0
  k=key[i]
  n=str(i)+'_'+str(k)+'_no'
  y=str(i)+'_'+str(k)+'_yes'
  for j in range(len(df)):
    if df[k][j]==0:
      no+=1
    elif df[k][j]==1:
      yes+=1
  di_1[n]=no
  di_1[y]=yes
dataf.append(di_1)

#음주 EDA
맥주=0
소주=0
양주=0
기타=99
di_2={}
for i in range(len(df)):
  if df['Type of Drink'][i]==0:
    맥주+=1
  elif df['Type of Drink'][i]==1:
    소주+=1
  elif df['Type of Drink'][i]==2:
    양주+=1
  else:
    기타+=1
di_2['34_drink_맥주']=맥주
di_2['34_drink_소주']=소주
di_2['34_drink_양주']=양주
di_2['34_drink_기타']=기타
dataf.append(di_2)

#흡연 EDA: class
xx=0
oo=0
o=0
di_3={}
for i in range(len(df)):
  if df['Smoke'][i]==0:
    xx+=1
  elif df['Smoke'][i]==1:
    oo+=1
  elif df['Smoke'][i]==2:
    o+=1
di_3['35_Smoke_비흡연']=xx
di_3['35_Smoke_현재흡연']=oo
di_3['35_Smoke_과거흡연']=o
dataf.append(di_3)

#초경
age_sum=0
age_min=99
age_max=0
response_o=0
response_x=0
for i in range(len(df)):
  if df['Age of Menarch'][i] != 99:
    response_o+=1
    age_sum+=df['Age of Menarch'][i]
    if df['Age of Menarch'][i]<age_min:
      age_min=df['Age of Menarch'][i]
    elif df['Age of Menarch'][i]>age_max:
      age_max=df['Age of Menarch'][i]
  else:
    response_x+=1
print(response_o)
print(response_x)
print(age_sum/len(df))
print(age_min)
print(age_max)

#폐경
age_sum=0
age_min=99
age_max=0
response_o=0
response_x=0
for i in range(len(df)):
  if df['Age of Menopause'][i] != 99:
    response_o+=1
    age_sum+=df['Age of Menopause'][i]
    if df['Age of Menopause'][i]<age_min:
      age_min=df['Age of Menopause'][i]
    elif df['Age of Menopause'][i]>age_max:
      age_max=df['Age of Menopause'][i]
  else:
    response_x+=1
print(response_o)
print(response_x)
print(age_sum/len(df))
print(age_min)
print(age_max)

#결혼
x=0
o=0
response_o=0
response_x=0
di_4={}
for i in range(len(df)):
  if df['Marriage'][i]==99:
    response_x+=1
  else:
    response_o+=1
    if df['Marriage'][i]==0:
      x+=1
    elif df['Marriage'][i]==1:
      o+=1
di_4['38_Marriage_no']=x
di_4['38_Marriage_yes']=o
dataf.append(di_4)

#출산연령
age_sum=0
age_min=99
age_max=0
response_o=0
response_x=0
for i in range(len(df)):
  if df['Age at first birth'][i] != 99:
    response_o+=1
    age_sum+=df['Age at first birth'][i]
    if df['Age at first birth'][i]<age_min:
      age_min=df['Age at first birth'][i]
    elif df['Age at first birth'][i]>age_max:
      age_max=df['Age at first birth'][i]
  else:
    response_x+=1
print(response_o)
print(response_x)
print(age_sum/len(df))
print(age_min)
print(age_max)

#출산자녀수
age_sum=0
age_min=99
age_max=0
response_o=0
response_x=0
for i in range(len(df)):
  if df['Number of births'][i] != 99:
    response_o+=1
    age_sum+=df['Number of births'][i]
    if df['Number of births'][i]<age_min:
      age_min=df['Number of births'][i]
    elif df['Number of births'][i]>age_max:
      age_max=df['Number of births'][i]
  else:
    response_x+=1
print(response_o)
print(response_x)
print(age_sum/len(df))
print(age_min)
print(age_max)

#COCP,HRT
di_5={}
for i in range(41,43):
  no=0
  yes=0
  k=key[i]
  n=str(i)+'_'+str(k)+'_no'
  y=str(i)+'_'+str(k)+'_yes'
  for j in range(len(df)):
    if df[k][j]==0:
      no+=1
    elif df[k][j]==1:
      yes+=1
  di_5[n]=no
  di_5[y]=yes
dataf.append(di_5)

#키
sum=0
min=5000
max=0
for i in range(len(df)):
  sum+=df['Height'][i]
  if df['Height'][i]<min:
    min=df['Height'][i]
  elif df['Height'][i]>max:
    max=df['Height'][i]
print(sum/len(df))
print(min)
print(max)

#몸무게
sum=0
min=5000
max=0
for i in range(len(df)):
  sum+=df['Weight'][i]
  if df['Weight'][i]<min:
    min=df['Weight'][i]
  elif df['Weight'][i]>max:
    max=df['Weight'][i]
print(sum/len(df))
print(min)
print(max)

#BRCA1 PVs~PR
di_6={}
for i in range(45,51):
  detect=0
  no_det=0
  response_o=0
  response_x=0
  k=key[i]
  n=str(i)+'_'+str(k)+'_detect'
  y=str(i)+'_'+str(k)+'_not detect'
  for j in range(len(df)):
    if df[k][j]==99:
      response_x+=1
    else:
      response_o+=1
      if df[k][j]==1:
        detect+=1
      elif df[k][j]==2:
        no_det+=1
  di_6[n]=detect
  di_6[y]=no_det
dataf.append(di_6)

#AR
di_7={}
detect=0
no_det=0
response_o=0
response_x=0
for j in range(len(df)):
  if df['AR'][j]==99 or df['AR'][j]==9:
    response_x+=1
  elif df['AR'][j]==1 or df['AR'][j]==2:
    response_o+=1
    if df['AR'][j]==1:
      detect+=1
    elif df['AR'][j]==2:
      no_det+=1
di_7['51_AR_detect']=detect
di_7['51_AR_not detect']=no_det
dataf.append(di_7)

#BCS,Mestectomy
di_8={}
for i in range(52,54):
  no=0
  yes=0
  response_o=0
  response_x=0
  k=key[i]
  n=str(i)+'_'+str(k)+'_no'
  y=str(i)+'_'+str(k)+'_yes'
  for j in range(len(df)):
    if df[k][j]==99:
      response_x+=1
    else:
      response_o+=1
      if df[k][j]==0:
        no+=1
      elif df[k][j]==1:
        yes+=1
  di_8[n]=no
  di_8[y]=yes
dataf.append(di_8)

#pan hysterosalpingo oophorectomy~Death
di_9={}
for i in range(54,59):
  no=0
  yes=0
  k=key[i]
  n=str(i)+'_'+str(k)+'_no'
  y=str(i)+'_'+str(k)+'_yes'
  for j in range(len(df)):
    if df[k][j]==0:
      no+=1
    elif df[k][j]==1:
      yes+=1
  di_9[n]=no
  di_9[y]=yes
dataf.append(di_9)

#암진단후생존일수
sum=0
min=100000
max=-1
for i in range(len(df)):
  sum+=df['Survival period'][i]
  if df['Survival period'][i]<min:
    min=df['Survival period'][i]
  elif df['Survival period'][i]>max:
    max=df['Survival period'][i]
print(sum/len(df))
print(min)
print(max)

dataf
